version: '3'

services:
  api:
    build: ./
    ports:
      - '3216:3216'
    volumes:
      - ./:/app
    depends_on:
      - db



  db:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5435:5435'
    # volumes: 
    #   - ./db:/var/lib/postgresql/data
    #   - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    # networks:
    #   - backnet

