version: '3'

services:
  api:
    build: ./
    ports:
      - '3216:3216'
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      DBUSER: ${DB_USERNAME}
      DBPASSWORD: ${DB_PASSWORD}



  db:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5435:5435'

  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_FRONTEND_URL=http://keycloak:8080
    ports:
      - '8080:8080'
    command: start-dev

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317" 


