"""Remove email field

Revision ID: 10924111a9b6
Revises: f3f11755698c
Create Date: 2025-05-25 07:13:58.014897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10924111a9b6'
down_revision: Union[str, None] = 'f3f11755698c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_email_key'), 'tasks', type_='unique')
    op.drop_column('tasks', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('tasks_email_key'), 'tasks', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
